### ISSUE TITLE
Add tutorial on fault tolerance

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.StarterKit#10]
Moved from https://github.com/elastacloud/mbrace-on-brisk-starter/issues/34

It would be great if someone could add a tutorial covering nice topics like these :)
•user-thrown exceptions
•unbounded computation in a process (with and without cloud-binds for cancellation)
•out-of-memory on a worker
•the different fault-tolerance models with examples

And possible also:
•storage catastrophes (storage full etc)
•process catastrophes (infinite production of processes etc)

**Comment by eiriktsarpalis** [comment]
Added in http://mbrace.io/starterkit/HandsOnTutorial/10-exceptions-and-fault-tolerance.html
