### ISSUE TITLE
Where is the client.fsx?

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#14]
Hi guys,

I want to test the custom service, but in the md file:
https://github.com/mbraceproject/MBrace.StarterKit/blob/master/azure/AZURE.md

it says:
6. Of using the hands-on tutorials, insert the same connection strings in client.fsx and connect to your runtime.

But I cannot find the client.fsx file, any hint?

**Comment by krontogiannis** [comment]
Hi, I've updated the md file to point to the correct fsx. You can insert the connection strings in [credentials.fsx](https://github.com/mbraceproject/MBrace.StarterKit/blob/master/azure/HandsOnTutorial/credentials.fsx) and get started with [hello-world.fsx](https://github.com/mbraceproject/MBrace.StarterKit/blob/master/azure/HandsOnTutorial/1-hello-world.fsx).

**Comment by soloman817** [comment]
so, what purpose of the custom serivice? I tested hello-world.fsx with a cluster deployed by brisk engine, and it works fine.

**Comment by krontogiannis** [comment]
It's just an alternative. Deployment using Brisk is definitely easier and faster experience, but by using the custom service you can customise the worker if you need to.

**Comment by soloman817** [comment]
thanks for the explanation, let me close this issue

**Comment by isaacabraham** [comment]
@krontogiannis: Do you have any ideas / suggestions for configuration or customisation that you would like to see exposed on brisk?

**Comment by krontogiannis** [comment]
I think it would be nice to be able customize the `MaxConcurrentJobs` at the point you create your cluster (and probably `Configuration.Id`); and very easy to implement.

**Comment by dsyme** [comment]
Pretty much any of these, taken from [here](http://www.m-brace.net/azure-tutorial.html#Provisioning-an-Azure-Cloud-Service-Explicitly)

* add endpoints to the cloud service (there are now one TCP and one HTTP by default)
* enable/disable Remote Access to MBrace cluster worker instances (now enabled by default)
* choose MBrace version by N.N.N or commit (I know we've discussed this and it's coming in due course :)) 
* adjust the size of VM used for worker instances in your cluster;
* specify the size of local storage available on MBrace cluster worker instances
* upload certificates as part of your provisioning process
* specify Azure-specific local caching options

**Comment by isaacabraham** [comment]
Cool, that's a good list. At least two of these are already in progress already, but its good to have a list!
