### ISSUE TITLE
How to handle long-live remote instance?

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#15]
Hi guys,

I tested mbrace today, and it is very nice. But I have one question which I cannot figure out from the examples. I know this is not an issue, but I would like to ask for some suggestions.

Say, we have a GPU library, which provides a type GPUModule, so usually we can create a type like:

```fsharp
type MyModule(gpu) =
    inherit GPUModule(gpu)
    ....
```

If you new an instance of this module type, you will get GPU code compiled and loaded in the specified GPU device which installed on your remote machine. Now I can create cloud monad like:

```fsharp
let job = 
    cloud {
        use mymodule = new MyModule(GPU.[0])
        return mymodule.Foo(blabla) }
    |> cluster.CreateProcess
```

The problem here is, the constructing of MyModule type is time-cost, it will compile GPU code and load it into GPU device, so it is not very good to create it each time you run the cloud computation. Is there a way to create a long-live remote instance for each worker? then in the cloud we can reference them?

One way I think might be using the custom serivce, and extend the worker to provide a way to store the compiled and loaded module, but again, in the custom service sample, I don't see how to extend the worker feature.

So, if any suggestion and hint, I appreciate that.

Regards,
Xiang.

**Comment by palladin** [comment]
Hi Xiang,
One possible approach is to have inside MyModule  something like a static field or a singletion to hold the expenssive resources.

**Comment by soloman817** [comment]
hi palladin,

thanks for your reply, so if I have

```fsharp
type MyModule(gpu) =
   inherit GPUModule(gpu)

   static Modules : Dictionary<string, GPUModule>
```

Then, will this static member be different in different worker?

say, in worker1, Modules.Count = 2
in worker2, Modules.Count = 4
etc.

Then which means, although it is static, but it is still static in machine scope, not cloud scope.

**Comment by palladin** [comment]
Yes ```static Modules : Dictionary<string, GPUModule> ``` lives inside an AppDomain. So it is different per worker role instance.

**Comment by soloman817** [comment]
Thanks very much, I think this is easier way than extend the worker like in custom service demo. I will try it tomorrow and then close this issue.

**Comment by soloman817** [comment]
@palladin 

I tested the static method, but looks like it has problem.

I first created an assembly, which contains the module type:

```fsharp
[<AOTCompile>]
type MyModule(target) =
    inherit GPUModule(target)

    let uuid = System.Guid.NewGuid()
    do printfn "construct %A" uuid

    static let instance = Lazy.Create <| fun _ -> new MyModule(GPUModuleTarget.DefaultWorker)

    static member Instance = instance.Value

    member this.Foo() =
        printfn "%A" uuid
        uuid
```

Then, I build this assembly, and reference it in the script then I use the static member:

```fsharp
let cluster = Runtime.GetHandle(config)
cluster.ShowWorkers()

let doJob(f : unit -> 'T) =
    let job = 
        [| 1 .. 3 |]
        |> CloudFlow.ofArray

        |> CloudFlow.map (fun i -> 
            let hostname = Dns.GetHostName()

            if hostname = "MACXIANG" then 
                f() |> Some
            else
                None)

        |> CloudFlow.toArray
        |> cluster.CreateProcess

    cluster.ShowProcesses()
    let results = job.AwaitResult()
    let result = results |> Array.choose id
    result.[0]

#r @"script-packages/MyApp.FS.exe"
open MyApp.FS

let test2() =
    let a = doJob <| fun _ ->
        use m = new MyModule(GPUModuleTarget.DefaultWorker)
        m.Foo()

    let b = doJob <| fun _ ->
        use m = new MyModule(GPUModuleTarget.DefaultWorker)
        m.Foo()

    printfn "a=%A" a
    printfn "b=%A" b

test2()
```

I force it to run on a worker on my local machine, so I get the log output, it looks like it constructs the static member twice. I got output like:

![2015-04-28_1503](https://cloud.githubusercontent.com/assets/3477345/7364336/15cdc4f8-edb8-11e4-9f17-b4e1a8727d88.png)

**Comment by soloman817** [comment]
@palladin this static method works perfectly! thanks, and I close this issue now.
