### ISSUE TITLE
Worker status not reset after long run

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#20]
Hi guys,

I ran a very big cloud compuation, which takes around 28 minutes, then, the process shows status "Completed", but the worker status looks like never been reset.

Please check my screenshot:

![2015-04-30_1819](https://cloud.githubusercontent.com/assets/3477345/7426554/a3723516-effa-11e4-9457-0e8516e4f130.png)

**Comment by krontogiannis** [comment]
Thanks, I'm closing this as there is a duplicate in the MBrace.Azure repo. Let's continue here  https://github.com/mbraceproject/MBrace.Azure/issues/75
