### ISSUE TITLE
If worker die, process status never been reset

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#21]
Hi guys,

I have 2 local workers, and one worker is slow to download assembly, so I just close it, and want to start a new local worker. But looks like the process is always "Running", so my last cloud call is always blocked. I think in this case, return exception is better than just blocking forever.

see the screenshot:
![2015-05-01_1156](https://cloud.githubusercontent.com/assets/3477345/7426637/a0a899d6-effc-11e4-8a1e-ba92e8644083.png)

**Comment by krontogiannis** [comment]
Hello, is your code using CloudFlow or Parallel/StartChild with WorkerRef affinity?

**Comment by soloman817** [comment]
@krontogiannis , I think I used CloudFlow

**Comment by krontogiannis** [comment]
Ok, so in cases with deterministic scheduling like CloudFlow or Parallel/etc with IWorkerRef, fault tolerance is incomplete (when the particular node doesn't restart or recover). I will close this issue, and post any updates here : https://github.com/mbraceproject/MBrace.Azure/issues/77
