### ISSUE TITLE
Exception of local worker when network has problem

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#22]
hi guys,

I opened a local worker, and since my network sometimes is not good, so I saw exceptions from time to time. and once these exception is thrown, this worker will never send heartbeat again, and looks like it is dead.

I then tested, if I shutdown the network, it immeditately throws exception. 

![2015-05-01_1233](https://cloud.githubusercontent.com/assets/3477345/7426743/64067f7c-efff-11e4-94a1-bed57ecdb207.png)

**Comment by krontogiannis** [comment]
Hello, which version do you use?

**Comment by soloman817** [comment]
@krontogiannis here it is:

```
nuget MBrace.Core 0.9.8-alpha
nuget MBrace.Flow 0.9.8-alpha
nuget MBrace.Azure 0.6.5-alpha
nuget MBrace.Azure.Standalone 0.6.5-alpha
nuget Alea.CUDA.Fody
nuget Alea.CUDA.Unbound
nuget Mono.Posix 4.0.0.0
```

**Comment by krontogiannis** [comment]
Fixed in https://github.com/mbraceproject/MBrace.Azure/commit/f0fdd0b958f071fa9e7b55cfa3c272a369083246
