### ISSUE TITLE
cannot start local worker

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#23]
Hi guys,

one of my test machine cannot start local worker. I connected to that machine through RDP, and it always has exception:

![2015-05-01_1243](https://cloud.githubusercontent.com/assets/3477345/7426762/e326f70a-efff-11e4-96e4-c398301efb08.png)

**Comment by krontogiannis** [comment]
Seem like the following code used to take the total machine's memory fails in that particular machine:
```fsharp
                use searcher = new ManagementObjectSearcher("root\\CIMV2", "SELECT TotalPhysicalMemory FROM Win32_ComputerSystem")
                use qObj = searcher.Get() 
                            |> Seq.cast<ManagementBaseObject> 
                            |> Seq.exactlyOne
                let totalBytes = qObj.["TotalPhysicalMemory"] :?> uint64
```

I'll add some code to handle the search failure, but no memory counters will be available for this worker.

(Unless there is a better way to get the machine's total memory)

**Comment by krontogiannis** [comment]
Fixed in https://github.com/mbraceproject/MBrace.Azure/commit/a6d5613e6b9641250d4227299c00c823ea719faf
