### ISSUE TITLE
how to handle subscription callback?

### ISSUE THREAD

**Issue by soloman817** [mbraceproject/MBrace.StarterKit#25]
Hi guys,

I'm thinking of how to implmenet this in mbrace + azure.

say, I want to implement a event subscription service. I have N nodes, which access the event service, and subscript an event topic by given a remote callback function. When other node triggers an event (e.g call one-way function in the event service), this event service then should find all subscribers for that event topic, and call all the remote callback functions.

Is that possible in mbrace? Would like to hear for some directions.

Regards,
Xiang.

**Comment by palladin** [comment]
Hi Xiang,
Currently, for such kind of scenarios the only possible solution is to use CloudChannels, for an example check the Mbrace.StarterKit https://github.com/mbraceproject/MBrace.StarterKit/blob/master/azure/HandsOnTutorial/400-using-cloud-channels.fsx

**Comment by soloman817** [comment]
@palladin  that is exactly the solution I think, but question, underlying, what protocol it uses? one-way udp? or two-way tcp? cause if we have many subscribers, one-way udp would be good choice.

**Comment by palladin** [comment]
@soloman817 The MBrace.Azure CloudChannel implementation is based on Azure ServiceBus queues.

**Comment by soloman817** [comment]
thanks, I close this issue :)
