### ISSUE TITLE
Failure when trying to launch external process from a cloud expression

### ISSUE THREAD

**Issue by jasonweiyi** [mbraceproject/MBrace.StarterKit#39]
I try to launch an external process from a cloud expression: I have python installed in C:\Python27 of the MBrace worker role machine, and I want to use the following code, which launches a python interpreter in the cloud expression:

// Create a Python file to extract link hrefs from a web page. 
let pythonCode = @"
from bs4 import BeautifulSoup
import sys
import json

lines = [line for line in sys.stdin]
text = '\n'.join(lines)
html = BeautifulSoup(text)
links = html.select('a')
hrefs = [link['href'] for link in links]

print(json.dumps(hrefs))
"

let job (url: string, pythonCode: string) = 
    cloud {
        // Download the web page.
        let content = (new WebClient()).DownloadString(url)
        
        // Create a temp file for the python code.
        let pythonFile = Path.GetTempFileName()
        File.WriteAllText(pythonFile, pythonCode)

        // Launch python interpreter to extract links.
        let prcInfo = ProcessStartInfo("c:\\Python27\\python.exe", pythonFile)
        prcInfo.UseShellExecute <- false
        prcInfo.RedirectStandardInput <- true
        prcInfo.RedirectStandardOutput <- true

        let prc = new Process()
        prc.StartInfo <- prcInfo
        prc.Start() |> ignore
        prc.StandardInput.Write(content)
        prc.StandardInput.Close()
        let output = prc.StandardOutput.ReadToEnd()
        prc.WaitForExit()
        let hrefs = JsonConvert.DeserializeObject<List<string>>(output);    
            
        // Delele the temp file.
        File.Delete(pythonFile)        
        return hrefs
    }
let result = job("http://www.m-brace.net/", pythonCode) |> cluster.Run

When I run this code, I got the following exception:

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at FSI_0063.job@56-3.Invoke(Unit unitVar)
   at MBrace.Core.Builders.Delay@287-1.Invoke(ExecutionContext ctx, Unit t) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\Builders.fs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Runtime-Core>.$CloudTask.AwaitResult@101-2.Invoke(TaskResult _arg2) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime.Core\Runtime\CloudTask.fs:line 101
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@797-1.Invoke(a a)
   at MBrace.Core.Internals.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\ExceptionDispatchInfo.fs:line 138
   at <StartupCode$FSI_0064>.$FSI_0064.main@() in C:\jasonw\git\my\MBrace.StarterKit3\azure\HandsOnTutorial\200-launching-python.fsx:line 86
Stopped due to error
> 
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at FSI_0065.job@56-4.Invoke(Unit unitVar)
   at MBrace.Core.Builders.Delay@287-1.Invoke(ExecutionContext ctx, Unit t) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\Builders.fs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Runtime-Core>.$CloudTask.AwaitResult@101-2.Invoke(TaskResult _arg2) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime.Core\Runtime\CloudTask.fs:line 101
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@797-1.Invoke(a a)
  at MBrace.Core.Internals.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\ExceptionDispatchInfo.fs:line 138
   at <StartupCode$FSI_0065>.$FSI_0065.main@() in C:\jasonw\git\my\MBrace.StarterKit3\azure\HandsOnTutorial\200-launching-python.fsx:line 80
Stopped due to error

I guess it is because the cloud expression does not have the right to run python.exe. How do I solve this?

**Comment by palladin** [comment]
Check if you can move your python files according to this http://stackoverflow.com/questions/8255852/starting-an-executable-file-in-an-azure-worker-role-path-problems

**Comment by palladin** [comment]
Check also this http://stackoverflow.com/questions/8725946/how-to-call-ffmpeg-exe-to-convert-audio-files-on-windows-azure

**Comment by dsyme** [comment]
And is it elevation?

**Comment by eiriktsarpalis** [comment]
On a slightly related note, we have developed a private implementation that parallelises a proprietary piece of software for a client using MBrace. We do this by uploading a zip archive of all required files to the blob store, then extract to each worker uniquely using the [DomainLocal](http://www.m-brace.net/reference/mbrace-library-domainlocal.html) construct. Perhaps the same could be done with the python installation. I'll see if I can publish a simplified version of the implimentation to the StarterKit.

**Comment by jasonweiyi** [comment]
The path should be correct, because when it is not correct, I got a
different error "The system cannot find the file specified". I'm trying to
elevate the worker role:
http://blogs.msdn.com/b/farida/archive/2012/05/01/run-the-azure-worker-role-in-elevated-mode-to-register-httplistener.aspx
right now.


On Fri, Sep 11, 2015 at 2:02 PM, Don Syme <notifications@github.com> wrote:

> And is it elevation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.StarterKit/issues/39#issuecomment-139540021>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by jasonweiyi** [comment]
Downloading a python folder from azure blog into the worker role works, I
tried it (but have not tried to launch python from cloud expression) the
other day. The script I showed before is for software which needs an
installation process.

On Fri, Sep 11, 2015 at 2:28 PM, Eirik Tsarpalis <notifications@github.com>
wrote:

> On a slightly related note, we have developed a private implementation
> that parallelises a proprietary piece of software for a client using
> MBrace. We do this by uploading a zip archive of all required files to the
> blob store, then extract to each worker uniquely using the DomainLocal
> <http://www.m-brace.net/reference/mbrace-library-domainlocal.html>
> construct. Perhaps the same could be done with the python installation.
> I'll see if I can publish a simplified version of the implimentation to the
> StarterKit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.StarterKit/issues/39#issuecomment-139545870>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by jasonweiyi** [comment]
Provision the worker roles in elevated mode (
http://blogs.msdn.com/b/farida/archive/2012/05/01/run-the-azure-worker-role-in-elevated-mode-to-register-httplistener.aspx)
solved the problem.

Thank you.

On Fri, Sep 11, 2015 at 2:35 PM, Wei Yi <jasonweiyi@gmail.com> wrote:

> Downloading a python folder from azure blog into the worker role works, I
> tried it (but have not tried to launch python from cloud expression) the
> other day. The script I showed before is for software which needs an
> installation process.
>
> On Fri, Sep 11, 2015 at 2:28 PM, Eirik Tsarpalis <notifications@github.com
> > wrote:
>
>> On a slightly related note, we have developed a private implementation
>> that parallelises a proprietary piece of software for a client using
>> MBrace. We do this by uploading a zip archive of all required files to the
>> blob store, then extract to each worker uniquely using the DomainLocal
>> <http://www.m-brace.net/reference/mbrace-library-domainlocal.html>
>> construct. Perhaps the same could be done with the python installation.
>> I'll see if I can publish a simplified version of the implimentation to the
>> StarterKit.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mbraceproject/MBrace.StarterKit/issues/39#issuecomment-139545870>
>> .
>>
>
>
>
> --
> Jason Wei
> Chair of Software Engineering, ETH Zurich
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich
