### ISSUE TITLE
MBrace.Thespian 1.1.8 NuGet pkg missing dependencies

### ISSUE THREAD

**Issue by evilpepperman** [mbraceproject/MBrace.StarterKit#84]
When using NuGet to fetch MBrace.Thespian 1.1.8, it says it's missing a dependency: "Thespian".  In the manifest, the dependency is "Thespian (>= 0.1.11-alpha && <0.2.0".

**Comment by eiriktsarpalis** [comment]
Strange, I'm getting this too. Was able to resolve it by installing Thespian first followed by MBrace.Thespian. Be sure to include prereleases too.

**Comment by evilpepperman** [comment]
That's it, Eirik!  I was expecting _Thespian_ to be fetched automatically.  As soon as I allow prerelease, and explicitly load _Thespian_, _MBrace.Thespian_ is fetched successfully.
