### ISSUE TITLE
Microsoft.WindowsAzure.Configuration.dll was not found at FSharp tutorial

### ISSUE THREAD

**Issue by vschep** [mbraceproject/MBrace.StarterKit#89]
I am trying to run MBrace on Azure. When executing 0-provision-azure-cluster.fsx line
`#load "AzureCluster.fsx"`
 I get 
`MBrace.Azure.fsx(14,1): error FS0084: Assembly reference 'tools/Microsoft.WindowsAzure.Configuration.dll' was not found or is invalid`
after doing paket install.

I built MBrace.Azure on my machine and copied 
MBrace.Azure\packages\Microsoft.WindowsAzure.ConfigurationManager\lib\net40\Microsoft.WindowsAzure.Configuration.dll to the directory
MBrace.StarterKit\packages\MBrace.Azure\tools
That solved this issue for the moment. 

The next exception occurs at 1-hello-world.fsx when executing
`let task = 
    cloud { return "Hello world!" } 
    |> cluster.CreateProcess`
Exception:
`Nessos.Vagabond.VagabondException: could not locate dependency 'Microsoft.Azure.KeyVault.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

I am running VS 2015 on Win7 and installed Azure SDK 2.9 and MicrosoftAzureLibsForNet-x64.msi of Azure SDK 2.7 since it's impossible to install Azure SDK 2.7 completely. The Microsoft Web Installer for Azure SDK 2.7 is broken.

I noticed that MBrace.StarterKit\HandsOnTutorial.FSharp\paket.references is empty. Is that correct? I copied all package names from paket.dependencies to paket.references, installed them and got them as references in the VS project but it didn't help either.

I would appreciate any help.

**Comment by smoothdeveloper** [comment]
Hello @vschep, I think paket.references is spurious because it is intended for use along *proj files but there aren't any since it is only scripts there.

Are you familiar with paket?

Could you make a project with `paket.dependencies` containing 

```
source https://www.nuget.org/api/v2

nuget MBrace.Azure.Management
```

run `paket install`

and then put the same script you are working on you'll need to adjust few paths to load those:

````fsharp
#load @"packages/MBrace.Azure/MBrace.Azure.fsx"
#load @"packages/MBrace.Azure.Management/MBrace.Azure.Management.fsx"
```
I think it should load all the stuff and allow you to get going.

**Comment by vschep** [comment]
Downgrading MBrace.Azure.Management to 1.3 solves the issue. Change lines 10 and 11 at `paket.dependencies` into

`nuget MBrace.Azure 1.3`
`nuget MBrace.Azure.Management 1.3`

Thanks to @smoothdeveloper helping me to solve this problem.

**Comment by eiriktsarpalis** [comment]
@vschep This is a packaging issue that has been fixed in MBrace.Azure 1.4.2. Thanks for reporting.
