### ISSUE TITLE
Add tutorial on auto-scaling 

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.StarterKit#9]
Copied from https://github.com/elastacloud/mbrace-on-brisk-starter/issues/35

I’ve been playing around with changing the cluster size while processing CPU-intensive jobs. Some notes are below.

I recommend we add a tutorial on the Azure cluster size and auto-scaling options to the Brisk getting-started information.

•Changing cluster size. I used the Azure portal to change the cluster size while processing CPU-intensive jobs. No problems so far, the services seem to be able to transition well. (Though I'm still waiting to see if jobs that were aborted due to a down-scaling transition are correctly restarted when using the fault-tolerance default settings)

•Auto-scale by CPU. I checked out Azure Cloud Service CPU auto-scaling for Brisk+MBrace. It works well enough. The auto-scale is not super-fast (Azure measures the service over an hour, then scales up if it’s been high CPU) but it at least give some degree of elasticity.

•Auto-scale by queue length. I haven't played with this yet. You can also auto-scale w.r.t. queue length which seems like it would work reasonably well for MBrace, given the MBrace work queue is used to mediate work in general. The defaults make transitions when there are ~2000 entries in the queue - for mbrace this would probably be more like 2-10 depending on granularities, since work feels like it will be much chunkier.

•Transitions and fault-tolerance. Either way, information on how the transitions are performed would be useful. Will a worker be brought down hard mid-computation? This is related to having a decent tutorial on fault-tolerance #34 )

I think it would be worth documenting the status of these options in the starter pack. It seems manually adjusting the cluster size up to 10 is a great way to experiment with a larger cluster, and automatic auto-scaling down to 1 worker is a great way to reduce costs when experimenting on and off.

Annoyingly the azure portal doesn't seem to remember your auto-scaling options as you switch auto-scaling on and off. I assume that these can be set via a management API as well.

**Comment by eiriktsarpalis** [comment]
Has been included in the MBrace.Azure.Management tutorial
